apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbide-api
  namespace: {{ include "carbide-api.namespace" . }}
  labels:
    {{- include "carbide-api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
