global:
  certificate:
    issuerRef:
      kind: Issuer
      name: local-ca-issuer
      group: cert-manager.io

carbide-api:
  automountServiceAccountToken: false
  migrationJob:
    enabled: true
    sslMode: disable
  vaultClusterInfo:
    VAULT_SERVICE: http://vault.vault.svc.cluster.local:8200
    FORGE_VAULT_MOUNT: secrets
    FORGE_VAULT_PKI_MOUNT: certs
  databaseConfig: {}
  extraEnv:
    - name: DISABLE_TLS_ENFORCEMENT
      value: "1"
