carbide-api:
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  siteConfig:
    enabled: true
    carbideApiSiteConfig: |
      bypass_rbac = true
      attestation_enabled = false
      dpu_ipmi_tool_impl = "test"
      initial_domain_name = "local.forge"
      initial_dpu_agent_upgrade_policy = "off"

      [pools.lo-ip]
      type = "ipv4"
      ranges = [{ start = "10.180.62.1", end = "10.180.62.62" }]

      [pools.vlan-id]
      type = "integer"
      ranges = [{ start = "100", end = "501" }]

      [pools.vni]
      type = "integer"
      ranges = [{ start = "1024500", end = "1024550" }]

      [pools.vpc-vni]
      type = "integer"
      ranges = [{ start = "2024500", end = "2024550" }]

      [networks.admin]
      type = "admin"
      prefix = "192.168.176.0/20"
      gateway = "192.168.176.1"
      mtu = 9000
      reserve_first = 0

      [networks.DEV-K3S-DPU-ACORN-0]
      type = "underlay"
      prefix = "192.168.192.0/20"
      gateway = "192.168.192.1"
      mtu = 1500
      reserve_first = 2

      [networks.DEV-K3S-X86-BMC-UNDERLAY-ACORN-X86-0]
      type = "underlay"
      prefix = "192.168.208.0/20"
      gateway = "192.168.208.1"
      mtu = 1500
      reserve_first = 2

      [auth]
      permissive_mode = true

      [auth.trust]
      spiffe_trust_domain = "forge.local"
      spiffe_service_base_paths = ["/forge-system/sa/", "/default/sa/"]
      spiffe_machine_base_path = "/forge-system/machine/"
      additional_issuer_cns = []

      [host_health]
      hardware_health_reports = "MonitorOnly"

      [machine_state_controller]
      dpu_wait_time = "1s"
      skip_polling_checks = true

      [machine_validation_config]
      enabled = false

      [site_explorer]
      enabled = true
      create_machines = true
      allow_changing_bmc_proxy = true
      allow_zero_dpu_hosts = true
      bmc_proxy = "machine-a-tron-bmc-mock.forge-system.svc.cluster.local:1266"
      run_interval = "10s"

      [firmware_global]
      autoupdate = true
      run_interval = "10s"
      concurrency_limit = 100

carbide-dhcp:
  enabled: false
carbide-dns:
  enabled: false
carbide-dsx-exchange-consumer:
  enabled: false
carbide-hardware-health:
  enabled: false
carbide-pxe:
  enabled: false
carbide-ssh-console-rs:
  enabled: false
unbound:
  enabled: false
