{{- if .Values.imagePullSecrets.ngcCarbidePull }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nvcr-carbide-dev
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"nvcr.io":{"username":"$oauthtoken","password":"%s"}}}` .Values.imagePullSecrets.ngcCarbidePull | b64enc }}
{{- end }}
{{- if .Values.imagePullSecrets.ngcNvidianKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nvcr-nvidian-nvforge
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{"nvcr.io":{"username":"$oauthtoken","password":"%s"}}}` .Values.imagePullSecrets.ngcNvidianKey | b64enc }}
{{- end }}
