[Output]
Output=qcow-imager
CompressOutput=zstd
CompressLevel=19

[Distribution]
Distribution=ubuntu
Release=noble
Repositories=main,restricted,universe,multiverse

[Build]
ToolsTree=default
Environment=MKOSI_CHROOT_SUPPRESS_CHOWN=1

[Content]
CleanPackageMetadata=yes
WithDocs=no
Packages=
     cloud-guest-utils
     curl
     debconf-utils
     dmidecode
     e2fsprogs
     efibootmgr
     fdisk
     file
     gdisk
     iproute2
     iputils-ping
     keyboard-configuration
     libargtable2-0
     libudev-dev
     linux-image-virtual
     lshw
     lvm2
     mstflint
     net-tools
     nvme-cli
     openssh-server
     parted
     pciutils
     qemu-utils
     smartmontools
     systemd-boot
     systemd-resolved
     systemd-timesyncd
     tpm2-tools
     util-linux
     vim-nox
     wget

RootPassword=password
